apiVersion: v1
kind: Pod
metadata:
  name: mynodepod
spec:
  containers:
  - name: mynodecontainer
    image: node:latest
    ports:
    - containerPort: 3000
    resources:
      limits:
        memory: "512Mi"
        cpu: "1"

