apiVersion: v1
kind: Pod
metadata:
  name: mypod2
  labels:
    label-name-2: label-value
spec:
  containers:
  - name: mycontainer22
    image: httpd
    resources:
      limits:
        memory: "512Mi"
        cpu: "1"
