apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    label-name-1: label-value
    another-label: my-app-name
spec:
  containers:
  - name: mycontainer
    image: nginx:alpine
    resources:
      limits:
        memory: "512Mi"
        cpu: "1"

